### ISSUE TITLE
Chrom name issue

### ISSUE THREAD

**Issue by OSchwich** [ZhengXia/dapars#12]
Dear all, 

after some time I came back using DaPars and ran into the following issue, using my config and annotations files I used before:
python2.7 ../dapars/src/DaPars_main.py Configure_file.txt
[Mon 17 Dec 2018 03:47:16 PM ] Start Analysis ...
[Mon 17 Dec 2018 03:47:16 PM ] Loading coverage ...
Traceback (most recent call last):
  File "../dapars/src/DaPars_main.py", line 548, in <module>
    De_Novo_3UTR_Identification_Loading_Target_Wig_for_TCGA_Multiple_Samples_Main(sys.argv)
  File "../dapars/src/DaPars_main.py", line 154, in De_Novo_3UTR_Identification_Loading_Target_Wig_for_TCGA_Multiple_Samples_Main
    All_samples_Target_3UTR_coverages, All_samples_sequencing_depths, UTR_events_dict = Load_Target_Wig_files(All_Sample_files, Annotated_3UTR_file)
  File "../dapars/src/DaPars_main.py", line 509, in Load_Target_Wig_files
    curr_sample_All_chroms_coverage_dict[chrom_name][1].append(0)
UnboundLocalError: local variable 'chrom_name' referenced before assignment

Would be happy if you can help me with this.

**Comment by obenno** [comment]
Hi,

May I ask is your chr named as chr1, chr2 in input bedgraph?

Bests,
obenno

**Comment by OSchwich** [comment]
That was the issue, I remapped against a gencode reference matching the chr1, chr2... nomenclature. 
It worked fine now. 

Best
